MongoClient/MongoFrontend/Controllers/RegistracijaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoFrontend.Models;
using System.Net.Http;

namespace MongoFrontend.Controllers
{
    public class RegistracijaController : Controller
    {
        // GET: Registracija
        public ActionResult Index()
        {
            if (Session["at"] != null)
            {
                return View("VecSteRegistrovani");
            }
            return View();
        }
        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> CreateKorisnik(Korisnik korisnik)
        {
            ///OVDE TREBA PROVERA DA LI JE USERNAME ZAUZET,
            ///AKO JESTE ONDA SE VRACA FORMA ZA REGISTRACIJU, A U VIEW BAG SE STAVLJA:
            ///NeuspesnaRegistracija=1    i    Ime=korisnik.Ime     i    Prezime=korisnik.Prezine
            ///AKO NIJE ZAUZET ONDA SE KORISNIK REGISTRUJE i RADI SE
            ///RedirectTo HomeIndexView

            if(korisnik==null)
            {
                return RedirectToAction("Index", "Home");
            }
            HttpClient client = HttpClientRepository.Client;
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Add("username", korisnik.Username);
            HttpResponseMessage response = await client.GetAsync(HttpClientRepository.Uri + "api/user");
            if (!response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");
            }

            Korisnik k = await response.Content.ReadAsAsync<Korisnik>();


            if(k!=null)
            {
                if (k.Username != null)
                {
                    //korisnik postoji u bazi
                    ViewBag.NeuspesnaRegistracija = 1;
                    ViewBag.Ime = korisnik.Ime;
                    ViewBag.Prezime = korisnik.Prezime;
                    return View("Index");
                }
            }

            //korisnik sa izabranim username ne postoji u bazi, moze da se doda

            response = await client.PostAsJsonAsync(HttpClientRepository.Uri + "api/user",korisnik);
            if(!response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");
            }

            AccessToken at = await response.Content.ReadAsAsync<AccessToken>();

            Session["username"] = korisnik.Username;
            Session["at"] = at.Access_token;

            return View("UspesnaRegistracija");
        }
    }
}

MongoClient/MongoFrontend/Views/Registracija/Index.cshtml
<h2>Registracija</h2>

@model MongoFrontend.Models.Korisnik

<div class="registracija-pozadina">
      <div class="registracija-vertical-place-up">
      </div>
      <div class="registracija-vertical-text-place">
            <div class="registracija-horizontal-space">
            </div>
            <div class="registracija-text-container">
                <div class="registacija-text-vert-space">
                </div>
                <div class="registracija-form-container">
                    <div class="registacija-text-hor-space">
                    </div>
                     @using (Html.BeginForm("CreateKorisnik", "Registracija", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "registracija-form", encType = "multipart/form-data" }))
                     {
                         @Html.AntiForgeryToken()

                          @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "registracija-form-element",@id="registracija-username" ,placeholder="Username" } })
                          if (ViewBag.NeuspesnaRegistracija!=null)
                          {
                            <p id="registracija-greska-text" style="color:red; text-align:center"> Username koji ste izabrali je vec zauzet! </p> 
                          }
                          @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "registracija-form-element", @id = "registracija-password", placeholder = "Password" } })

                          @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "registracija-form-element", placeholder = "Ime", @id = "registracija-ime", @Value = @ViewBag.Ime } })

                         @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "registracija-form-element", placeholder = "Prezime", @id = "registracija-prezime", @Value = @ViewBag.Prezime } })

                         <input type="submit" value="Registrujte se" class="registracija-form-element" id="registracija-btn"/>
                     }
                    <div class="registacija-text-hor-space">
                    </div>
                </div>
                <div class="registacija-text-vert-space">
                </div>
            </div>
            <div class="registracija-horizontal-space">
            </div>
      </div>
      <div class="registracija-vertical-place-down">
      </div>
</div>

<script src="@Url.Content("../../Scripts/Registracija.js")" type="text/javascript"></script>

MongoClient/MongoFrontend/Views/Registracija/UspesnaRegistracija.cshtml
@{
    ViewBag.Title = "Registracija";
}

<h2 style="height:450px; margin-top:80px">Uspesno ste se registrovali!</h2>

MongoClient/MongoFrontend/Views/Registracija/VecSteRegistrovani.cshtml
@{
    ViewBag.Title = "Registracija";
}

<h2 style="color:red; height:450px; margin-top:100px">Vec ste registrovani!</h2>