MongoClient/MongoFrontend/Controllers/PrijavaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoFrontend.Models;
using System.Net.Http;
using System.Web.Security;

namespace MongoFrontend.Controllers
{
    public class PrijavaController : Controller
    {
        public ActionResult Index()
        {
            if (Session["at"] != null)
            {
                return View("VecStePrijavljeni");
            }
            return View();
        }
        public async System.Threading.Tasks.Task<ActionResult> PrijaviKorisnika(Korisnik korisnik)
        {
            //// OVDE TREBA DA SE PROVERI DA LI U BAZI POSTOJI KORISNIK SA DATIM USERNAME I PASS
            /// AKO POSTOJI, KORISNIK SE PRIJAVLJUJE
            /// AKO NE POSTOJI VRACA SE STRANICA ZA PRIJAVU A U ViewBag SE STAVLJA
            /// NeuspesnaPrijava=1;


            HttpClient client = HttpClientRepository.Client;
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Add("username", korisnik.Username);
            client.DefaultRequestHeaders.Add("password", korisnik.Password);
            HttpResponseMessage response = await client.GetAsync(HttpClientRepository.Uri + "api/login");
            if(response.ReasonPhrase.Equals("No account."))
            {
                ViewBag.NeuspesnaPrijava = 1;
                return View("Index");
            }
            if (!response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");
            }
            AccessToken at =await response.Content.ReadAsAsync<AccessToken>();
            Session["Username"] = korisnik.Username;
            Session["at"] = at.Access_token;

            return View("UspesnaPrijava");
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }
}

MongoClient/MongoFrontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Akordi</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap Dropdown Hover CSS -->
    <link href="css/animate.min.css" rel="stylesheet">
    <link href="css/bootstrap-dropdownhover.min.css" rel="stylesheet">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container container-flex">
            <div class="navbar-header navbar-item">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pocetna", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="dropdown">
                <button class="btn btn-default dropdown-toggle btn-dropdown" type="button" data-toggle="dropdown" data-hover="dropdown">
                    Akordi <span class="caret"></span>
                </button>
               
                <ul class="dropdown-menu">
                    
                </ul>
            </div>
            <div class="navbar-space"> 
            </div>
            
            <div class="navbar-collapse collapse navbar-item">
                <ul class="nav navbar-nav">
                    <li id="layout-prikaz-imena" class="a">@Context.Session["username"]</li>
                    @if (@Context.Session["username"] != null && @Context.Session["at"] != null)
                    {
                        <li>@Html.ActionLink("Dodaj akorde", "DodavanjePesme", "Pesma")</li>
                        <li>@Html.ActionLink("Odjava", "Logout", "Prijava")</li>
                    }
                    @if (@Context.Session["username"] == null)
                    {
                        <li>@Html.ActionLink("Prijava", "Index", "Prijava")</li>
                        <li>@Html.ActionLink("Registracija", "Index", "Registracija")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - HmTeam</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Bootstrap Dropdown Hover JS -->
    <script src="js/bootstrap-dropdownhover.min.js"></script>
    <script src="@Url.Content("../../Scripts/layout.js")" type="text/javascript"></script>
</body>
</html>